### ISSUE TITLE
[PATCH] fix a recurrent POD syntax error

### ISSUE THREAD

**Issue by gregoa** [mattp-/Data-Perl#5]
In Debian we are currently applying the following patch to Data-Perl.
We thought you might be interested in it too.

This looks a bit like https://github.com/mattp-/Data-Perl/pull/4
but there only one occurence is fixed.

(And the fix is the other way round, by adding instead of removing bullets,
which is of course also fine :))

Description: fix a recurrent POD syntax error:
 'Expected text after =item, not a bullet'
Origin: vendor
Author: gregor herrmann gregoa@debian.org
Last-Update: 2014-06-26

The patch is tracked in our Git repository at
http://anonscm.debian.org/gitweb/?p=pkg-perl/packages/libdata-perl-perl.git;a=blob;f=debian/patches/pod-syntax.patch;hb=HEAD

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by mattp-** [comment]
Gregor,
I've applied this patch and cut a new release. Thanks!

Matt

**Comment by gregoa** [comment]
On Thu, 26 Jun 2014 18:04:53 -0700, Matt Phillips wrote:

> Gregor,
> I've applied this patch and cut a new release. Thanks!

Awesome, thanks!

And uploaded to Debian/unstable.

Cheers,
gregor

## 

 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer  -  http://www.debian.org/
`. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
`\-   NP: Don McLean: American Pie
